//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UrTBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Commands : global::System.Configuration.ApplicationSettingsBase {
        
        private static Commands defaultInstance = ((Commands)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Commands())));
        
        public static Commands Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Min. Level needed to change others level.
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Min. Level needed to change others level.")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LevelLevel {
            get {
                return ((int)(this["LevelLevel"]));
            }
            set {
                this["LevelLevel"] = value;
            }
        }
        
        /// <summary>
        /// Level needed to kick
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Level needed to kick")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int KickLevel {
            get {
                return ((int)(this["KickLevel"]));
            }
            set {
                this["KickLevel"] = value;
            }
        }
        
        /// <summary>
        /// Level needed to slap
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Level needed to slap")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SlapLevel {
            get {
                return ((int)(this["SlapLevel"]));
            }
            set {
                this["SlapLevel"] = value;
            }
        }
        
        /// <summary>
        /// Level needed to mute
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Level needed to mute")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MuteLevel {
            get {
                return ((int)(this["MuteLevel"]));
            }
            set {
                this["MuteLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int NukeLevel {
            get {
                return ((int)(this["NukeLevel"]));
            }
            set {
                this["NukeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int BanLevel {
            get {
                return ((int)(this["BanLevel"]));
            }
            set {
                this["BanLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int InfoLevel {
            get {
                return ((int)(this["InfoLevel"]));
            }
            set {
                this["InfoLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int TellLevel {
            get {
                return ((int)(this["TellLevel"]));
            }
            set {
                this["TellLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int LocationLevel {
            get {
                return ((int)(this["LocationLevel"]));
            }
            set {
                this["LocationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ForceLevel {
            get {
                return ((int)(this["ForceLevel"]));
            }
            set {
                this["ForceLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int VetoLevel {
            get {
                return ((int)(this["VetoLevel"]));
            }
            set {
                this["VetoLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RCONLevel {
            get {
                return ((int)(this["RCONLevel"]));
            }
            set {
                this["RCONLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BigtextLevel {
            get {
                return ((int)(this["BigtextLevel"]));
            }
            set {
                this["BigtextLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SayLevel {
            get {
                return ((int)(this["SayLevel"]));
            }
            set {
                this["SayLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TimeLevel {
            get {
                return ((int)(this["TimeLevel"]));
            }
            set {
                this["TimeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AdminsLevel {
            get {
                return ((int)(this["AdminsLevel"]));
            }
            set {
                this["AdminsLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int StartStopBotLevel {
            get {
                return ((int)(this["StartStopBotLevel"]));
            }
            set {
                this["StartStopBotLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int ShuffleteamsLevel {
            get {
                return ((int)(this["ShuffleteamsLevel"]));
            }
            set {
                this["ShuffleteamsLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int Swapteamslevel {
            get {
                return ((int)(this["Swapteamslevel"]));
            }
            set {
                this["Swapteamslevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MapLevel {
            get {
                return ((int)(this["MapLevel"]));
            }
            set {
                this["MapLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int NextmapLevel {
            get {
                return ((int)(this["NextmapLevel"]));
            }
            set {
                this["NextmapLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MaprestartLevel {
            get {
                return ((int)(this["MaprestartLevel"]));
            }
            set {
                this["MaprestartLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MapreloadLevel {
            get {
                return ((int)(this["MapreloadLevel"]));
            }
            set {
                this["MapreloadLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int TeamsLevel {
            get {
                return ((int)(this["TeamsLevel"]));
            }
            set {
                this["TeamsLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int PauseLevel {
            get {
                return ((int)(this["PauseLevel"]));
            }
            set {
                this["PauseLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ServerInfoLevel {
            get {
                return ((int)(this["ServerInfoLevel"]));
            }
            set {
                this["ServerInfoLevel"] = value;
            }
        }
    }
}
